/* Auto-generated from Portfolio/Images. Do not edit by hand. */
window.PORTFOLIO_IMAGE_CATALOG = [
  { path: "assets/library/01 Unreal Engine/Maserati-Ghibli/Maserati-Ghibli-detail.jpg", format: "wide", type: "image", version: "101c6a-8daed205a88d600", comment: null },
  { path: "assets/library/01 Unreal Engine/Maserati-Ghibli/Maserati-Ghibli-interior.jpg", format: "wide", type: "image", version: "d2e58-8daf1f0bfe13900", comment: null },
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-back.jpg", format: "wide", type: "image", version: "8fc14-8d5a61fc9a4a200", comment: null },
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-front.jpg", format: "wide", type: "image", version: "8603a-8d5a61fc9a4a200", comment: null },
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-interior.jpg", format: "wide", type: "image", version: "5d3fa-8d5a61fc9a4a200", comment: null },
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-motion.jpg", format: "wide", type: "image", version: "5cde5-8d5a61fc9a4a200", comment: null },
  { path: "assets/library/02 Rendering/mpio-player.jpg", format: "wide", type: "image", version: "29265-8d59aa6c4cfe200", comment: "product render" },
  { path: "assets/library/02 Rendering/visualization-of-shelves-1.jpg", format: "wide", type: "image", version: "30ae8-8d59aa6c4cfe200", comment: "product render" },
  { path: "assets/library/02 Rendering/visualization-of-shelves-2.jpg", format: "wide", type: "image", version: "330d5-8d59aa6c4cfe200", comment: "product render" },
  { path: "assets/library/02 Rendering/zemeklon.jpg", format: "portrait", type: "image", version: "5525a-8d59df675671a00", comment: "Some fun with 3DsMax nad Vray" },
  { path: "assets/library/03 PC Games/Day-Z/apartment-building-exterior.jpg", format: "wide", type: "image", version: "fee84-8d59aa67d495600", comment: null },
  { path: "assets/library/03 PC Games/Day-Z/apartment-building-interior.jpg", format: "wide", type: "image", version: "111da6-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Day-Z/ship-wreck-1.jpg", format: "wide", type: "image", version: "e1ac1-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Day-Z/ship-wreck-2.jpg", format: "wide", type: "image", version: "5428e-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Day-Z/ship-wreck-3.jpg", format: "wide", type: "image", version: "4e8fb-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Mafia II/balls-&-beans-1.jpg", format: "wide", type: "image", version: "368b3-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Mafia II/balls-&-beans-2.jpg", format: "wide", type: "image", version: "57812-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Mafia II/cossack-car.jpg", format: "wide", type: "image", version: "45f33-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Mafia II/greenfield-flat.jpg", format: "wide", type: "image", version: "43dae-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/03 PC Games/Mafia II/uptown-flat-1.jpg", format: "wide", type: "image", version: "63221-8d59aa6a10c9c00", comment: "All stuff is my work, except kitchen desk." },
  { path: "assets/library/03 PC Games/Mafia II/uptown-flat-2.jpg", format: "wide", type: "image", version: "4cd0c-8d59aa6a10c9c00", comment: "All stuff is my work, except fridge and fox ;)" },
  { path: "assets/library/03 PC Games/Mafia II/uptown-flat-3.jpg", format: "wide", type: "image", version: "55871-8d59aa6a10c9c00", comment: "All stuff is my work, except bed." },
  { path: "assets/library/04 3d-print/kicom.jpg", format: "square", type: "image", version: "651d7-8defaaa5c79c1fa", comment: null },
  { path: "assets/library/04 3d-print/mahakala.jpg", format: "portrait", type: "image", version: "4b26d-8defaaa60f08743", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/3D-print-1.gif", format: "wide", type: "image", version: "456ecb-8d59aa67d495600", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/3D-print-2.gif", format: "wide", type: "image", version: "14fcab-8d59aa67d495600", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/3D-print-3.gif", format: "wide", type: "image", version: "1eddcf-8d59aa67d495600", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/3D-print-4.gif", format: "square", type: "image", version: "c82fb-8d59aa67d495600", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/all_characters_poster.jpg", format: "wide", type: "image", version: "4d137-8d5a4a33fcfca00", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/animation.jpg", format: "square", type: "image", version: "31fd8-8d59aa67d495600", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/krmitko_poster.jpg", format: "wide", type: "image", version: "94e3c-8d59aa67d495600", comment: null },
  { path: "assets/library/04 3d-print/Radio Impuls/piskoviste_poster.jpg", format: "wide", type: "image", version: "70a2d-8d59aa67d495600", comment: null },
  { path: "assets/library/04 3d-print/Starship/starship-flat.jpg", format: "wide", type: "image", version: "13b159-8defaaa5dc2946d", comment: null },
  { path: "assets/library/04 3d-print/Starship/starshi-top.jpg", format: "portrait", type: "image", version: "1f6a1-8defaaa5e7e13bc", comment: null },
  { path: "assets/library/05 Visualization - Fibix Realtime/crib/crib.mp4", format: "wide", type: "video", version: "3805fa-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/05 Visualization - Fibix Realtime/crib/crib-2.jpg", format: "wide", type: "image", version: "d331b-8d59aa6a10c9c00", comment: "Real-time rendered visualization for developers purposes in early times of Fibix editor. All stuff is my work." },
  { path: "assets/library/05 Visualization - Fibix Realtime/crib/crib-5.jpg", format: "wide", type: "image", version: "cbfa9-8d59aa6a10c9c00", comment: "Real-time rendered visualization for developers purposes in early times of Fibix editor. All stuff is my work." },
  { path: "assets/library/05 Visualization - Fibix Realtime/gallery/gallery.mp4", format: "wide", type: "video", version: "2bf84f1-8d59aa6c4cfe200", comment: null },
  { path: "assets/library/05 Visualization - Fibix Realtime/gallery/gallery-exterior-1.jpg", format: "wide", type: "image", version: "f6e11-8d59aa6c4cfe200", comment: "First real project for Fibix studio. Visualization reconstruction of the gallery and cafe in Mariánské Lázně." },
  { path: "assets/library/05 Visualization - Fibix Realtime/gallery/gallery-interior-1.jpg", format: "wide", type: "image", version: "a89cb-8d59aa6c4cfe200", comment: "First real project for Fibix studio. Visualization reconstruction of the gallery and cafe in Mariánské Lázně." },
  { path: "assets/library/05 Visualization - Fibix Realtime/gallery/gallery-interior-of-cafe-1.jpg", format: "wide", type: "image", version: "90d45-8d59aa6c4cfe200", comment: "First real project for Fibix studio. Visualization reconstruction of the gallery and cafe in Mariánské Lázně." },
  { path: "assets/library/05 Visualization - Fibix Realtime/vila-lignum/vila-lignum.mp4", format: "wide", type: "video", version: "438b96-8d59aa6c4cfe200", comment: null },
  { path: "assets/library/05 Visualization - Fibix Realtime/vila-lignum/vila-lignum-1.jpg", format: "wide", type: "image", version: "99a71-8d59aa6c4cfe200", comment: "Real-time rendered visualization for presentation of capabilities of Fibix editor. All stuff is my work. Architecture is based on reference of real house." },
  { path: "assets/library/05 Visualization - Fibix Realtime/vila-lignum/vila-lignum-4.jpg", format: "wide", type: "image", version: "b6149-8d59aa6c4cfe200", comment: "Real-time rendered visualization for presentation of capabilities of Fibix editor. All stuff is my work. Architecture is based on reference of real house." },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-background-1.jpg", format: "wide", type: "image", version: "6b15b-8d59aa67d495600", comment: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-background-2.jpg", format: "wide", type: "image", version: "7fdda-8d59aa67d495600", comment: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-characters.jpg", format: "portrait", type: "image", version: "ac72a-8d59aa67d495600", comment: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-cihelna-exterier.jpg", format: "wide", type: "image", version: "8c61b-8d59aa67d495600", comment: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-cihelna-interier.jpg", format: "wide", type: "image", version: "62541-8d59aa67d495600", comment: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-maya.jpg", format: "portrait", type: "image", version: "4828f-8d5a61fc9a4a200", comment: null },
  { path: "assets/library/oldies/High poly Ferrari 550 back front.jpg", format: "square", type: "image", version: "3c56d-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/oldies/High poly Ferrari 550 back.jpg", format: "square", type: "image", version: "481eb-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/oldies/High poly Ferrari 550 detail.jpg", format: "square", type: "image", version: "572ce-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/oldies/lowpoly Porsche_limit 3000 polygonu_pro pouziti do hry.jpg", format: "square", type: "image", version: "37ac5-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/oldies/lowpoly Porsche_limit 3000 polygonu_pro pouziti do hry2.jpg", format: "square", type: "image", version: "423dc-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/oldies/redbull-plane.jpg", format: "wide", type: "image", version: "6d857-8d59aa6a10c9c00", comment: null },
  { path: "assets/library/oldies/Wesserflug P.1003.jpg", format: "wide", type: "image", version: "166f7-8def9ea62db6a5f", comment: null },
  { path: "assets/library/oldies/Wesserflug P.1003_front_dobovy.jpg", format: "wide", type: "image", version: "15395-8def9ea62dc6d42", comment: null },
  { path: "assets/library/oldies/yach-front-wire.jpg", format: "square", type: "image", version: "3136e-8d5a61fc9a4a200", comment: null },
  { path: "assets/library/oldies/yacht-back.jpg", format: "wide", type: "image", version: "4bba5-8d5a61fc9a4a200", comment: null },
  { path: "assets/library/oldies/yacht-front.jpg", format: "wide", type: "image", version: "4b9d0-8d5a61fc9a4a200", comment: null },
];
window.PORTFOLIO_FOLDER_METADATA = {
};
