/* Auto-generated from Portfolio/Images. Do not edit by hand. */
window.PORTFOLIO_IMAGE_CATALOG = [
  { path: "assets/library/3d-print/files/3D-print-1.gif", format: "wide" },
  { path: "assets/library/3d-print/files/3D-print-2.gif", format: "wide" },
  { path: "assets/library/3d-print/files/3D-print-3.gif", format: "wide" },
  { path: "assets/library/3d-print/files/3D-print-4.gif", format: "square" },
  { path: "assets/library/3d-print/files/all_characters_poster.jpg", format: "wide" },
  { path: "assets/library/3d-print/files/animation.jpg", format: "square" },
  { path: "assets/library/3d-print/files/krmitko_poster.jpg", format: "wide" },
  { path: "assets/library/3d-print/files/piskoviste_poster.jpg", format: "wide" },
  { path: "assets/library/3d-print/wip/kicom-max-screen.jpg", format: "square" },
  { path: "assets/library/3d-print/wip/mahakala-screenshot.jpg", format: "portrait" },
  { path: "assets/library/Čtyřlístek ve službách krále - MOVIE/ctyrlistek-ve-sluzbach-krale-background-1.jpg", format: "wide" },
  { path: "assets/library/Čtyřlístek ve službách krále - MOVIE/ctyrlistek-ve-sluzbach-krale-background-2.jpg", format: "wide" },
  { path: "assets/library/Čtyřlístek ve službách krále - MOVIE/ctyrlistek-ve-sluzbach-krale-characters.jpg", format: "portrait" },
  { path: "assets/library/Čtyřlístek ve službách krále - MOVIE/ctyrlistek-ve-sluzbach-krale-cihelna-exterier.jpg", format: "wide" },
  { path: "assets/library/Čtyřlístek ve službách krále - MOVIE/ctyrlistek-ve-sluzbach-krale-cihelna-interier.jpg", format: "wide" },
  { path: "assets/library/Čtyřlístek ve službách krále - MOVIE/ctyrlistek-ve-sluzbach-krale-maya.jpg", format: "portrait" },
  { path: "assets/library/Day-Z - PC Game/apartment-building-exterior.jpg", format: "wide" },
  { path: "assets/library/Day-Z - PC Game/apartment-building-interior.jpg", format: "wide" },
  { path: "assets/library/Day-Z - PC Game/ship-wreck-1.jpg", format: "wide" },
  { path: "assets/library/Day-Z - PC Game/ship-wreck-2.jpg", format: "wide" },
  { path: "assets/library/Day-Z - PC Game/ship-wreck-3.jpg", format: "wide" },
  { path: "assets/library/high-poly/ferrari/ferrari-back.jpg", format: "wide" },
  { path: "assets/library/high-poly/ferrari/ferrari-front.jpg", format: "wide" },
  { path: "assets/library/high-poly/redbull-plane/redbull-plane.jpg", format: "wide" },
  { path: "assets/library/Mafia II - PC Game/balls-&-beans-1.jpg", format: "wide" },
  { path: "assets/library/Mafia II - PC Game/balls-&-beans-2.jpg", format: "wide" },
  { path: "assets/library/Mafia II - PC Game/cossack-car.jpg", format: "wide" },
  { path: "assets/library/Mafia II - PC Game/greenfield-flat.jpg", format: "wide" },
  { path: "assets/library/Mafia II - PC Game/uptown-flat-1.jpg", format: "wide" },
  { path: "assets/library/Mafia II - PC Game/uptown-flat-2.jpg", format: "wide" },
  { path: "assets/library/Mafia II - PC Game/uptown-flat-3.jpg", format: "wide" },
  { path: "assets/library/oldies/High poly Ferrari 550 back front.jpg", format: "square" },
  { path: "assets/library/oldies/High poly Ferrari 550 back.jpg", format: "square" },
  { path: "assets/library/oldies/High poly Ferrari 550 detail.jpg", format: "square" },
  { path: "assets/library/oldies/lowpoly Porsche_limit 3000 polygonu_pro pouziti do hry.jpg", format: "square" },
  { path: "assets/library/oldies/lowpoly Porsche_limit 3000 polygonu_pro pouziti do hry2.jpg", format: "square" },
  { path: "assets/library/oldies/Wesserflug P.1003.jpg", format: "wide" },
  { path: "assets/library/oldies/Wesserflug P.1003_front_dobovy.jpg", format: "wide" },
  { path: "assets/library/oldies/yach-front-wire.jpg", format: "square" },
  { path: "assets/library/oldies/yacht-back.jpg", format: "wide" },
  { path: "assets/library/oldies/yacht-front.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/crib/crib-2.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/crib/crib-3.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/crib/crib-5.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/gallery/gallery-exterior-1.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/gallery/gallery-interior-1.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/gallery/gallery-interior-of-cafe-1.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/vila-lignum/vila-lignum-1.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/vila-lignum/vila-lignum-3.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/vila-lignum/vila-lignum-4.jpg", format: "wide" },
  { path: "assets/library/realtime-visualization/vila-lignum/vila-lignum-5.jpg", format: "wide" },
  { path: "assets/library/rendering/alfa-romeo/alfa-romeo-c8-spider-back.jpg", format: "wide" },
  { path: "assets/library/rendering/alfa-romeo/alfa-romeo-c8-spider-front.jpg", format: "wide" },
  { path: "assets/library/rendering/alfa-romeo/alfa-romeo-c8-spider-interior.jpg", format: "wide" },
  { path: "assets/library/rendering/alfa-romeo/alfa-romeo-c8-spider-motion.jpg", format: "wide" },
  { path: "assets/library/rendering/mpio/mpio-player.jpg", format: "wide" },
  { path: "assets/library/rendering/shelves/visualization-of-shelves-1.jpg", format: "wide" },
  { path: "assets/library/rendering/shelves/visualization-of-shelves-2.jpg", format: "wide" },
  { path: "assets/library/rendering/zemeklon/zemeklon.jpg", format: "portrait" },
  { path: "assets/library/Take On - PC Game/space-needle-01.jpg", format: "wide" },
  { path: "assets/library/Take On - PC Game/space-needle-02.jpg", format: "wide" },
  { path: "assets/library/Take On - PC Game/takeon-cover.png", format: "square" },
  { path: "assets/library/unreal/Maserati-Ghibli/Maserati-Ghibli-detail.jpg", format: "wide" },
  { path: "assets/library/unreal/Maserati-Ghibli/Maserati-Ghibli-interior.jpg", format: "wide" },
];
