/* Auto-generated from Portfolio/Images. Do not edit by hand. */
window.PORTFOLIO_IMAGE_CATALOG = [
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-back.jpg", format: "wide", type: "image", version: "8fc14-8d5a61fc9a4a200", title: null, description: null },
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-front.jpg", format: "wide", type: "image", version: "8603a-8d5a61fc9a4a200", title: null, description: null },
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-interior.jpg", format: "wide", type: "image", version: "5d3fa-8d5a61fc9a4a200", title: null, description: null },
  { path: "assets/library/02 Rendering/alfa-romeo/alfa-romeo-c8-spider-motion.jpg", format: "wide", type: "image", version: "5cde5-8d5a61fc9a4a200", title: null, description: null },
  { path: "assets/library/02 Rendering/Maserati-Ghibli/Maserati-Ghibli-detail.jpg", format: "wide", type: "image", version: "101c6a-8daed205a88d600", title: null, description: null },
  { path: "assets/library/02 Rendering/Maserati-Ghibli/Maserati-Ghibli-interior.jpg", format: "wide", type: "image", version: "d2e58-8daf1f0bfe13900", title: null, description: null },
  { path: "assets/library/02 Rendering/Product Render/mpio-player.jpg", format: "wide", type: "image", version: "29265-8d59aa6c4cfe200", title: null, description: "product render" },
  { path: "assets/library/02 Rendering/Product Render/visualization-of-shelves-1.jpg", format: "wide", type: "image", version: "30ae8-8d59aa6c4cfe200", title: null, description: "product render" },
  { path: "assets/library/02 Rendering/Product Render/visualization-of-shelves-2.jpg", format: "wide", type: "image", version: "330d5-8d59aa6c4cfe200", title: null, description: "product render" },
  { path: "assets/library/02 Rendering/zemeklon.jpg", format: "portrait", type: "image", version: "5525a-8d59df675671a00", title: null, description: "Some fun with 3DsMax nad Vray" },
  { path: "assets/library/03 PC Games/01 Mafia II/balls-&-beans-1.jpg", format: "wide", type: "image", version: "368b3-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/03 PC Games/01 Mafia II/balls-&-beans-2.jpg", format: "wide", type: "image", version: "57812-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/03 PC Games/01 Mafia II/cossack-car.jpg", format: "wide", type: "image", version: "45f33-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/03 PC Games/01 Mafia II/greenfield-flat.jpg", format: "wide", type: "image", version: "43dae-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/03 PC Games/01 Mafia II/uptown-flat-1.jpg", format: "wide", type: "image", version: "6082f-8d59aa6a10c9c00", title: null, description: "All stuff is my work, except kitchen desk." },
  { path: "assets/library/03 PC Games/01 Mafia II/uptown-flat-2.jpg", format: "wide", type: "image", version: "4a92e-8d59aa6a10c9c00", title: null, description: "All stuff is my work, except fridge and fox ;)" },
  { path: "assets/library/03 PC Games/01 Mafia II/uptown-flat-3.jpg", format: "wide", type: "image", version: "5428f-8d59aa6a10c9c00", title: null, description: "All stuff is my work, except bed." },
  { path: "assets/library/03 PC Games/02 Day-Z/apartment-building-exterior.jpg", format: "wide", type: "image", version: "fee84-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/03 PC Games/02 Day-Z/apartment-building-interior.jpg", format: "wide", type: "image", version: "111da6-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/03 PC Games/02 Day-Z/ship-wreck-1.jpg", format: "wide", type: "image", version: "e1ac1-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/03 PC Games/02 Day-Z/ship-wreck-2.jpg", format: "wide", type: "image", version: "5428e-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/03 PC Games/02 Day-Z/ship-wreck-3.jpg", format: "wide", type: "image", version: "4e8fb-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/3D-print-1.gif", format: "wide", type: "image", version: "456ecb-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/3D-print-2.gif", format: "wide", type: "image", version: "14fcab-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/3D-print-3.gif", format: "wide", type: "image", version: "1eddcf-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/3D-print-4.gif", format: "square", type: "image", version: "c82fb-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/all_characters_poster.jpg", format: "wide", type: "image", version: "4d137-8d5a4a33fcfca00", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/animation.jpg", format: "square", type: "image", version: "31fd8-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/krmitko_poster.jpg", format: "wide", type: "image", version: "94e3c-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/04 3d-print/Radio Impuls - Advertising/piskoviste_poster.jpg", format: "wide", type: "image", version: "70a2d-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/04 3d-print/Sculptures/kicom.jpg", format: "square", type: "image", version: "651d7-8defaaa5c79c1fa", title: null, description: null },
  { path: "assets/library/04 3d-print/Sculptures/mahakala.jpg", format: "portrait", type: "image", version: "4b26d-8defaaa60f08743", title: null, description: null },
  { path: "assets/library/04 3d-print/Starship/starship-flat.jpg", format: "wide", type: "image", version: "13b159-8defaaa5dc2946d", title: null, description: null },
  { path: "assets/library/04 3d-print/Starship/starshi-top.jpg", format: "portrait", type: "image", version: "1f6a1-8defaaa5e7e13bc", title: null, description: null },
  { path: "assets/library/05 Visualization/Galerie Edison/gallery.mp4", format: "wide", type: "video", version: "2bf84f1-8d59aa6c4cfe200", title: null, description: null },
  { path: "assets/library/05 Visualization/Galerie Edison/gallery-exterior-1.jpg", format: "wide", type: "image", version: "f548b-8d59aa6c4cfe200", title: null, description: "First real project for Fibix studio. Visualization reconstruction of the gallery and cafe in Mariánské Lázně." },
  { path: "assets/library/05 Visualization/Galerie Edison/gallery-interior-1.jpg", format: "wide", type: "image", version: "a6ffb-8d59aa6c4cfe200", title: null, description: "First real project for Fibix studio. Visualization reconstruction of the gallery and cafe in Mariánské Lázně." },
  { path: "assets/library/05 Visualization/Galerie Edison/gallery-interior-of-cafe-1.jpg", format: "wide", type: "image", version: "8f36b-8d59aa6c4cfe200", title: null, description: "First real project for Fibix studio. Visualization reconstruction of the gallery and cafe in Mariánské Lázně." },
  { path: "assets/library/05 Visualization/Log House/crib.mp4", format: "wide", type: "video", version: "3805fa-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/05 Visualization/Log House/crib-2.jpg", format: "wide", type: "image", version: "d1455-8d59aa6a10c9c00", title: null, description: "Real-time rendered visualization for developers purposes in early times of Fibix editor. All stuff is my work." },
  { path: "assets/library/05 Visualization/Log House/crib-5.jpg", format: "wide", type: "image", version: "ca10b-8d59aa6a10c9c00", title: null, description: "Real-time rendered visualization for developers purposes in early times of Fibix editor. All stuff is my work." },
  { path: "assets/library/05 Visualization/Vila Lignum/vila-lignum.mp4", format: "wide", type: "video", version: "438b96-8d59aa6c4cfe200", title: null, description: null },
  { path: "assets/library/05 Visualization/Vila Lignum/vila-lignum-1.jpg", format: "wide", type: "image", version: "97e47-8d59aa6c4cfe200", title: null, description: "Real-time rendered visualization for presentation of capabilities of Fibix editor. All stuff is my work. Architecture is based on reference of real house." },
  { path: "assets/library/05 Visualization/Vila Lignum/vila-lignum-4.jpg", format: "wide", type: "image", version: "b44b5-8d59aa6c4cfe200", title: null, description: "Real-time rendered visualization for presentation of capabilities of Fibix editor. All stuff is my work. Architecture is based on reference of real house." },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-background-1.jpg", format: "wide", type: "image", version: "6b15b-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-background-2.jpg", format: "wide", type: "image", version: "7fdda-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-characters.jpg", format: "portrait", type: "image", version: "ac72a-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-cihelna-exterier.jpg", format: "wide", type: "image", version: "8c61b-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-cihelna-interier.jpg", format: "wide", type: "image", version: "62541-8d59aa67d495600", title: null, description: null },
  { path: "assets/library/Cartoon/Čtyřlístek- MOVIE/ctyrlistek-ve-sluzbach-krale-maya.jpg", format: "portrait", type: "image", version: "4828f-8d5a61fc9a4a200", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/High poly Ferrari 550 back front.jpg", format: "square", type: "image", version: "3c5ba-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/High poly Ferrari 550 back.jpg", format: "square", type: "image", version: "46d04-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/High poly Ferrari 550 detail.jpg", format: "square", type: "image", version: "5731b-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/lowpoly Porsche_limit 3000 polygonu_pro pouziti do hry.jpg", format: "square", type: "image", version: "37b29-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/lowpoly Porsche_limit 3000 polygonu_pro pouziti do hry2.jpg", format: "square", type: "image", version: "42440-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/redbull-plane.jpg", format: "wide", type: "image", version: "6d857-8d59aa6a10c9c00", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/Wesserflug P.1003.jpg", format: "wide", type: "image", version: "166f7-8defb4dcfb80fb3", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/Wesserflug P.1003_front_dobovy.jpg", format: "wide", type: "image", version: "15395-8defb4dcfb9d546", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/yach-front-wire.jpg", format: "square", type: "image", version: "3136e-8d5a61fc9a4a200", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/yacht-back.jpg", format: "wide", type: "image", version: "4bba5-8d5a61fc9a4a200", title: null, description: null },
  { path: "assets/library/Oldies - 3D Assets/yacht-front.jpg", format: "wide", type: "image", version: "4b9d0-8d5a61fc9a4a200", title: null, description: null },
];
window.PORTFOLIO_FOLDER_METADATA = {
  "03 PC Games": { markdown: "I create production-ready 3D assets for game development, from modeling and texturing to optimization and implementation, with experience on titles including Mafia II and DayZ.", url: null },
  "05 Visualization": { markdown: "2010 - Graphic support for earlies versions of software \r\rReal-time rendered visualization for presentation of capabilities of Fibix editor.", url: null },
};
